DELETE http://localhost:3000/api/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk2ODhjMWM0ZWNhZWM3ZmJkMzYxYjMiLCJpYXQiOjE2MjA0NzgxNDV9.nGcIo7z-HqV-SLR_WEk30mSJBNamutbC23TWewZNnGk

{
}