POST http://localhost:3000/api/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk2YzBmZTFlZmU0OGVkN2E0NTE2NjgiLCJpYXQiOjE2MjA0OTI1NDJ9.UudleTwBYMLFvPp4auWsgnCZDNmJ3d9EIw707Pdq66o

{
}